services:
  rocketmq-namesrv:
    image: apache/rocketmq:5.1.0
    container_name: rocketmq-namesrv
    ports:
      - "9876:9876"
    environment:
      - JAVA_OPT_EXT=-Xms512M -Xmx512M
    command: sh mqnamesrv
    volumes:
      - ./data/namesrv/logs:/home/rocketmq/logs

  rocketmq-broker:
    image: apache/rocketmq:5.1.0
    container_name: rocketmq-broker
    ports:
      - "10909:10909"
      - "10911:10911"
    environment:
      - NAMESRV_ADDR=rocketmq-namesrv:9876
      - JAVA_OPT_EXT=-Xms512M -Xmx512M
    command: sh mqbroker -n rocketmq-namesrv:9876
    depends_on:
      - rocketmq-namesrv
    volumes:
      - ./data/broker/logs:/home/rocketmq/logs
      - ./data/broker/store:/home/rocketmq/store
      - ../conf/broker.conf:/home/rocketmq/conf/broker.conf

  rocketmq-console:
    image: styletang/rocketmq-console-ng
    container_name: rocketmq-console
    ports:
      - "8081:8080"
    environment:
      - JAVA_OPTS=-Xms256M -Xmx256M
    depends_on:
      - rocketmq-namesrv
      - rocketmq-broker

  mysql:
    image: mysql:8.0
    container_name: rocketmq-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=opc.tang2026
      - MYSQL_DATABASE=rocketmq_orderly
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ../sql:/docker-entrypoint-initdb.d
