spring:
  application:
    name: rocketmq-orderly

  datasource:
    url: jdbc:mysql://localhost:3306/rocketmq_orderly?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: opc.tang2026
    driver-class-name: com.mysql.cj.jdbc.Driver

  rocketmq:
    name-server: localhost:9876
    producer:
      group: order-producer-rocketmq

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.common.entity

logging:
  level:
    com.example: DEBUG
    org.apache.rocketmq: INFO
